<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Statistics | UMass PBS Instructors R Manual</title>
  <meta name="description" content="A guide for instructors teaching statistics and research methods with R in the UMass Amherst Psychological &amp; Brain Sciences Department." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Statistics | UMass PBS Instructors R Manual" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A guide for instructors teaching statistics and research methods with R in the UMass Amherst Psychological &amp; Brain Sciences Department." />
  <meta name="github-repo" content="wjhopper/PBS-R-Manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Statistics | UMass PBS Instructors R Manual" />
  
  <meta name="twitter:description" content="A guide for instructors teaching statistics and research methods with R in the UMass Amherst Psychological &amp; Brain Sciences Department." />
  

<meta name="author" content="Andrea Cataldo &amp; Will Hopper" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r-programming-fundamentals.html">
<link rel="next" href="tools-advice-for-instructors.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html">UMass PBS Instructors R Manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-started"><i class="fa fa-check"></i>Getting Started</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-r-language"><i class="fa fa-check"></i>The R Language</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#rstudio"><i class="fa fa-check"></i>RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#formatting-conventions"><i class="fa fa-check"></i>Formatting Conventions</a></li>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#additional-materials"><i class="fa fa-check"></i><b>0.1</b> Additional Materials</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Introducing R and RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#console"><i class="fa fa-check"></i><b>1.1</b> Pane #1: The R Console</a></li>
<li class="chapter" data-level="1.2" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#pane-2-the-editor"><i class="fa fa-check"></i><b>1.2</b> Pane #2: The Editor</a></li>
<li class="chapter" data-level="1.3" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#pane-3-your-r-session"><i class="fa fa-check"></i><b>1.3</b> Pane #3: Your R Session</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#variables-and-the-environment"><i class="fa fa-check"></i><b>1.3.1</b> Variables and the Environment</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#pane-4-miscellaneous"><i class="fa fa-check"></i><b>1.4</b> Pane #4: Miscellaneous</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#plots"><i class="fa fa-check"></i><b>1.4.1</b> Plots</a></li>
<li class="chapter" data-level="1.4.2" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#packages"><i class="fa fa-check"></i><b>1.4.2</b> Packages</a></li>
<li class="chapter" data-level="1.4.3" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#help"><i class="fa fa-check"></i><b>1.4.3</b> Help</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introducing-r-and-rstudio.html"><a href="introducing-r-and-rstudio.html#conclusion"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html"><i class="fa fa-check"></i><b>2</b> R Programming Fundamentals</a><ul>
<li class="chapter" data-level="2.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#classes-of-data"><i class="fa fa-check"></i><b>2.1</b> Classes of Data</a><ul>
<li class="chapter" data-level="2.1.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#the-numeric-class"><i class="fa fa-check"></i><b>2.1.1</b> The Numeric Class</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#the-integer-class"><i class="fa fa-check"></i><b>2.1.2</b> The Integer Class</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#logicals"><i class="fa fa-check"></i><b>2.1.3</b> The Logical Class</a></li>
<li class="chapter" data-level="2.1.4" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#the-character-class"><i class="fa fa-check"></i><b>2.1.4</b> The Character Class</a></li>
<li class="chapter" data-level="2.1.5" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#factors"><i class="fa fa-check"></i><b>2.1.5</b> Factors</a></li>
<li class="chapter" data-level="2.1.6" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#class-detection-and-conversion"><i class="fa fa-check"></i><b>2.1.6</b> Class detection and conversion</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#data-structures"><i class="fa fa-check"></i><b>2.2</b> Data Structures</a><ul>
<li class="chapter" data-level="2.2.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#vectors"><i class="fa fa-check"></i><b>2.2.1</b> Vectors</a></li>
<li class="chapter" data-level="2.2.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#matrices"><i class="fa fa-check"></i><b>2.2.2</b> Matrices</a></li>
<li class="chapter" data-level="2.2.3" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#data-frames"><i class="fa fa-check"></i><b>2.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="2.2.4" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#lists"><i class="fa fa-check"></i><b>2.2.4</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#operators"><i class="fa fa-check"></i><b>2.3</b> Operators</a><ul>
<li class="chapter" data-level="2.3.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#relational-operators"><i class="fa fa-check"></i><b>2.3.1</b> Relational Operators</a></li>
<li class="chapter" data-level="2.3.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#logical-operators"><i class="fa fa-check"></i><b>2.3.2</b> Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#functions"><i class="fa fa-check"></i><b>2.4</b> Functions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#description"><i class="fa fa-check"></i><b>2.4.1</b> Description</a></li>
<li class="chapter" data-level="2.4.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#usage"><i class="fa fa-check"></i><b>2.4.2</b> Usage</a></li>
<li class="chapter" data-level="2.4.3" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#arguments"><i class="fa fa-check"></i><b>2.4.3</b> Arguments</a></li>
<li class="chapter" data-level="2.4.4" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#named-vs.-unnamed-arguments"><i class="fa fa-check"></i><b>2.4.4</b> Named vs. Unnamed Arguments</a></li>
<li class="chapter" data-level="2.4.5" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#a-word-of-advice-2"><i class="fa fa-check"></i><b>2.4.5</b> A word of advice</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#data-manipulation"><i class="fa fa-check"></i><b>2.5</b> Data Manipulation</a><ul>
<li class="chapter" data-level="2.5.1" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#tidy-data"><i class="fa fa-check"></i><b>2.5.1</b> Tidy Data</a></li>
<li class="chapter" data-level="2.5.2" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#importing-data"><i class="fa fa-check"></i><b>2.5.2</b> Importing Data</a></li>
<li class="chapter" data-level="2.5.3" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#subsetting"><i class="fa fa-check"></i><b>2.5.3</b> Subsetting</a></li>
<li class="chapter" data-level="2.5.4" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#indexing"><i class="fa fa-check"></i><b>2.5.4</b> Indexing</a></li>
<li class="chapter" data-level="2.5.5" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#replacement"><i class="fa fa-check"></i><b>2.5.5</b> Replacement</a></li>
<li class="chapter" data-level="2.5.6" data-path="r-programming-fundamentals.html"><a href="r-programming-fundamentals.html#matrices-data-frames"><i class="fa fa-check"></i><b>2.5.6</b> Matrices &amp; Data Frames</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>3</b> Statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="statistics.html"><a href="statistics.html#the-data"><i class="fa fa-check"></i><b>3.1</b> The Data</a></li>
<li class="chapter" data-level="3.2" data-path="statistics.html"><a href="statistics.html#formula-objects"><i class="fa fa-check"></i><b>3.2</b> Formula Objects</a></li>
<li class="chapter" data-level="3.3" data-path="statistics.html"><a href="statistics.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.3</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.3.1" data-path="statistics.html"><a href="statistics.html#mean"><i class="fa fa-check"></i><b>3.3.1</b> Mean</a></li>
<li class="chapter" data-level="3.3.2" data-path="statistics.html"><a href="statistics.html#median"><i class="fa fa-check"></i><b>3.3.2</b> Median</a></li>
<li class="chapter" data-level="3.3.3" data-path="statistics.html"><a href="statistics.html#variance"><i class="fa fa-check"></i><b>3.3.3</b> Variance</a></li>
<li class="chapter" data-level="3.3.4" data-path="statistics.html"><a href="statistics.html#standard-deviation"><i class="fa fa-check"></i><b>3.3.4</b> Standard Deviation</a></li>
<li class="chapter" data-level="3.3.5" data-path="statistics.html"><a href="statistics.html#standard-error"><i class="fa fa-check"></i><b>3.3.5</b> Standard Error</a></li>
<li class="chapter" data-level="3.3.6" data-path="statistics.html"><a href="statistics.html#correlation"><i class="fa fa-check"></i><b>3.3.6</b> Correlation</a></li>
<li class="chapter" data-level="3.3.7" data-path="statistics.html"><a href="statistics.html#summary-functions"><i class="fa fa-check"></i><b>3.3.7</b> Summary Functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="statistics.html"><a href="statistics.html#plotting"><i class="fa fa-check"></i><b>3.4</b> Plotting</a><ul>
<li class="chapter" data-level="3.4.1" data-path="statistics.html"><a href="statistics.html#scatter-line-plots"><i class="fa fa-check"></i><b>3.4.1</b> Scatter &amp; Line Plots</a></li>
<li class="chapter" data-level="3.4.2" data-path="statistics.html"><a href="statistics.html#barplots"><i class="fa fa-check"></i><b>3.4.2</b> Barplots</a></li>
<li class="chapter" data-level="3.4.3" data-path="statistics.html"><a href="statistics.html#histograms"><i class="fa fa-check"></i><b>3.4.3</b> Histograms</a></li>
<li class="chapter" data-level="3.4.4" data-path="statistics.html"><a href="statistics.html#boxplots"><i class="fa fa-check"></i><b>3.4.4</b> Boxplots</a></li>
<li class="chapter" data-level="3.4.5" data-path="statistics.html"><a href="statistics.html#configuring-plots"><i class="fa fa-check"></i><b>3.4.5</b> Configuring Plots</a></li>
<li class="chapter" data-level="3.4.6" data-path="statistics.html"><a href="statistics.html#what-about-ggplot"><i class="fa fa-check"></i><b>3.4.6</b> What about ggplot?</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="statistics.html"><a href="statistics.html#inferential-statistics"><i class="fa fa-check"></i><b>3.5</b> Inferential Statistics</a><ul>
<li class="chapter" data-level="3.5.1" data-path="statistics.html"><a href="statistics.html#distribution-functions"><i class="fa fa-check"></i><b>3.5.1</b> Distribution Functions</a></li>
<li class="chapter" data-level="3.5.2" data-path="statistics.html"><a href="statistics.html#t.test"><i class="fa fa-check"></i><b>3.5.2</b> <code>t.test()</code></a></li>
<li class="chapter" data-level="3.5.3" data-path="statistics.html"><a href="statistics.html#aov"><i class="fa fa-check"></i><b>3.5.3</b> <code>aov()</code></a></li>
<li class="chapter" data-level="3.5.4" data-path="statistics.html"><a href="statistics.html#cor.test"><i class="fa fa-check"></i><b>3.5.4</b> <code>cor.test()</code></a></li>
<li class="chapter" data-level="3.5.5" data-path="statistics.html"><a href="statistics.html#binom.test"><i class="fa fa-check"></i><b>3.5.5</b> <code>binom.test()</code></a></li>
<li class="chapter" data-level="3.5.6" data-path="statistics.html"><a href="statistics.html#chisq.test"><i class="fa fa-check"></i><b>3.5.6</b> <code>chisq.test()</code></a></li>
<li class="chapter" data-level="3.5.7" data-path="statistics.html"><a href="statistics.html#lm"><i class="fa fa-check"></i><b>3.5.7</b> <code>lm()</code></a></li>
<li class="chapter" data-level="3.5.8" data-path="statistics.html"><a href="statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>3.5.8</b> Confidence Intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html"><i class="fa fa-check"></i><b>4</b> Tools &amp; Advice for Instructors</a><ul>
<li class="chapter" data-level="4.1" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#best-practices"><i class="fa fa-check"></i><b>4.1</b> Best Practices</a><ul>
<li class="chapter" data-level="4.1.1" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#commands-vs.-buttons"><i class="fa fa-check"></i><b>4.1.1</b> Commands vs. Buttons</a></li>
<li class="chapter" data-level="4.1.2" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#naming-objects"><i class="fa fa-check"></i><b>4.1.2</b> Naming Objects</a></li>
<li class="chapter" data-level="4.1.3" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#scripting"><i class="fa fa-check"></i><b>4.1.3</b> Scripting</a></li>
<li class="chapter" data-level="4.1.4" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#formatting-requirements-for-assignments"><i class="fa fa-check"></i><b>4.1.4</b> Formatting Requirements for Assignments</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-messages"><i class="fa fa-check"></i><b>4.2</b> Error Messages</a><ul>
<li class="chapter" data-level="4.2.1" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#there-is-no-output-from-a-command-and-there-is-a-in-the-console-instead-of-a-."><i class="fa fa-check"></i><b>4.2.1</b> There is no output from a command, and there is a <code>+</code> in the console instead of a <code>&gt;</code>.</a></li>
<li class="chapter" data-level="4.2.2" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-unexpected-in-___"><i class="fa fa-check"></i><b>4.2.2</b> <code>Error: unexpected ')' in '___'</code></a></li>
<li class="chapter" data-level="4.2.3" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-object-___-not-found"><i class="fa fa-check"></i><b>4.2.3</b> <code>Error: Object '___' not found</code></a></li>
<li class="chapter" data-level="4.2.4" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-in-___-non-numeric-argument-to-binary-operator"><i class="fa fa-check"></i><b>4.2.4</b> <code>Error in ___ : non-numeric argument to binary operator</code></a></li>
<li class="chapter" data-level="4.2.5" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-in-___x-could-not-find-function-___"><i class="fa fa-check"></i><b>4.2.5</b> <code>Error in ___(x) : could not find function '___'</code></a></li>
<li class="chapter" data-level="4.2.6" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-in-___-cannot-open-the-connection"><i class="fa fa-check"></i><b>4.2.6</b> <code>Error in ___ : cannot open the connection</code></a></li>
<li class="chapter" data-level="4.2.7" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-in-___-undefined-columns-selected-or-error-in-___-subscript-out-of-bounds"><i class="fa fa-check"></i><b>4.2.7</b> <code>Error in ___ : undefined columns selected** or **Error in ___: subscript out of bounds</code></a></li>
<li class="chapter" data-level="4.2.8" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#error-unexpected-symbol-in-___"><i class="fa fa-check"></i><b>4.2.8</b> <code>Error: unexpected symbol in '___'</code></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#data-sets"><i class="fa fa-check"></i><b>4.3</b> Data Sets</a><ul>
<li class="chapter" data-level="4.3.1" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#built-in"><i class="fa fa-check"></i><b>4.3.1</b> Built-In</a></li>
<li class="chapter" data-level="4.3.2" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#fivethirtyeight"><i class="fa fa-check"></i><b>4.3.2</b> FiveThirtyEight</a></li>
<li class="chapter" data-level="4.3.3" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#psych"><i class="fa fa-check"></i><b>4.3.3</b> psych</a></li>
<li class="chapter" data-level="4.3.4" data-path="tools-advice-for-instructors.html"><a href="tools-advice-for-instructors.html#simulating-your-own-data-sets"><i class="fa fa-check"></i><b>4.3.4</b> Simulating your own Data Sets</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">UMass PBS Instructors R Manual</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Statistics</h1>
<div id="the-data" class="section level2">
<h2><span class="header-section-number">3.1</span> The Data</h2>
<p>We rely on the <code>sat.act</code> data set from the <code>psych</code> package for all demonstrations in this chapter.</p>
<p>To make the data set available on your own computer, run the following code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&#39;psych&#39;</span>)
<span class="kw">library</span>(psych)</code></pre>
<p>You should now be able to access the <code>sat.act</code> data set:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(sat.act)</code></pre>
<pre><code>##      gender        education          age             ACT       
##  Min.   :1.000   Min.   :0.000   Min.   :13.00   Min.   : 3.00  
##  1st Qu.:1.000   1st Qu.:3.000   1st Qu.:19.00   1st Qu.:25.00  
##  Median :2.000   Median :3.000   Median :22.00   Median :29.00  
##  Mean   :1.647   Mean   :3.164   Mean   :25.59   Mean   :28.55  
##  3rd Qu.:2.000   3rd Qu.:4.000   3rd Qu.:29.00   3rd Qu.:32.00  
##  Max.   :2.000   Max.   :5.000   Max.   :65.00   Max.   :36.00  
##                                                                 
##       SATV            SATQ      
##  Min.   :200.0   Min.   :200.0  
##  1st Qu.:550.0   1st Qu.:530.0  
##  Median :620.0   Median :620.0  
##  Mean   :612.2   Mean   :610.2  
##  3rd Qu.:700.0   3rd Qu.:700.0  
##  Max.   :800.0   Max.   :800.0  
##                  NA&#39;s   :13</code></pre>
<p>As you can see, this data set includes self-reported SAT and ACT scores along with demographic information from 700 respondents. It therefore contains both categorical and continuous variables that are appropriate for both within- and between-subjects analyses. For more information, refer to the help documentation by running the command <code>?sat.act</code>.</p>
</div>
<div id="formula-objects" class="section level2">
<h2><span class="header-section-number">3.2</span> Formula Objects</h2>
<p>Formulas are special objects in R that are used in a range of functions discussed in this chapter, notably <code>plot()</code>, <code>aov()</code>, and <code>lm()</code>. The use of formulas in these specific functions will be discussed in more detail below, but we first introduce their general properties here.</p>
<p>The basic structure is as follows:</p>
<p><code>y ~ x</code></p>
<p>The <code>y</code> variable is the dependent variable, the <code>x</code> variable is the independent variable, and the <code>~</code> operator can be taken to mean “as a function of”. Thus, the above example is a formula for “y as a function fo x”.</p>
<p>For a more concrete example, consider the effect of the independent variable age on the dependent variable ACT scores:</p>
<p><code>sat.act$ACT ~ sat.act$age</code></p>
<p>We can have multiple independent variables in the formula. For instance, if we wanted to define ACT scores as a function of age and education, we would do so as follows:</p>
<p><code>sat.act$ACT ~ sat.act$age + sat.act$education</code></p>
<p>The above formula is an example of an “additive” model, in which ACT scores are a function of the additive effects of age and education. To define the interactive model, we would separate age and education by an asterisk instead of a plus sign:</p>
<p><code>sat.act$ACT ~ sat.act$age*sat.act$education</code></p>
<p>Note that the above formula defines the <em>full</em> interactive model, so ACT scores are defined as a function of (1) the main effect of age, (2) the main effect of education, and (3) the interaction of age and education. This same model can be implemented by definind each components separately in the formula object, like this:</p>
<p><code>sat.act$ACT ~ sat.act$age + sat.act$education + sat.act$age:sat.act$education</code></p>
<p>By defining the components separately, you can pick and choose which to keep. For instance, you could specify only the main effect of age and the interaction of age and education, as follows:</p>
<p><code>sat.act$ACT ~ sat.act$age + sat.act$age:sat.act$education</code></p>
<p>Formulas can get much more complex than the examples here, which only extend as far necessary for the functions and tests that you are likely to use as an instructor in undergraduate psychology program. A comprehensive tutorial can be found <a href="https://www.datacamp.com/community/tutorials/r-formula-tutorial">here</a>.</p>
</div>
<div id="descriptive-statistics" class="section level2">
<h2><span class="header-section-number">3.3</span> Descriptive Statistics</h2>
<div id="mean" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Mean</h3>
</div>
<div id="median" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Median</h3>
</div>
<div id="variance" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Variance</h3>
</div>
<div id="standard-deviation" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Standard Deviation</h3>
</div>
<div id="standard-error" class="section level3">
<h3><span class="header-section-number">3.3.5</span> Standard Error</h3>
</div>
<div id="correlation" class="section level3">
<h3><span class="header-section-number">3.3.6</span> Correlation</h3>
</div>
<div id="summary-functions" class="section level3">
<h3><span class="header-section-number">3.3.7</span> Summary Functions</h3>
</div>
</div>
<div id="plotting" class="section level2">
<h2><span class="header-section-number">3.4</span> Plotting</h2>
<p>One of the most compelling reason to learn and use is because it includes highly flexible and powerful tools for visualizing many kinds of data. After all, if a single tool can perform your analyses and create your figures, why not use the “one ring to rule them all”?</p>
<p>Many visualizations can be created using the <code>plot()</code> function, so we’ll begin our introduction using that function. As you’ll soon see, the <code>plot()</code> function accepts many arguments, as there are many ways to customize a plot. Many of the other visualiation tools in R accept similar arguments. So, if <code>plot()</code> accepts an argument, there is a fair chance another function will accept it as well.</p>
<div id="scatter-line-plots" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Scatter &amp; Line Plots</h3>
<p>If you have two vectors representing pairs of observations, you can plot them against one another in a scatter plot using the <code>plot()</code> function. Let’s demonstrate this by plotting the SAT Verbal and SAT Quantitative scores from the <code>sat.act</code> dataset against one another.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ) <span class="co"># Access the columns as vectors using $ syntax</span></code></pre>
<p><img src="statistics_files/figure-html/basicplot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The points in the plot above represent pairs SAT Verbal and SAT Quantitative scores. The scores in each vector are paired up by position within each vector - the first value in <code>SATV</code> is paired with the first value in <code>SATQ</code>, the second value in <code>SATV</code> is paired with the second value in <code>SATQ</code>, etc. The vector given as the first argument determines the X axis position, and the vector given as the second argument determines the Y axis position.</p>
<p>The axis titles are determined by the variable names of the vectors supplied to the <code>plot</code> function. However, variable names aren’t always the most informative names for other humans to read. We can customize the axes and plot with infomative titles using the <code>xlab</code>, <code>ylab</code> and <code>main</code> arguments for the <code>plot</code> function:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ,
     <span class="dt">xlab =</span> <span class="st">&quot;SAT Verbal&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;SAT Quantitative&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Relationship between SAT Scores&quot;</span>)</code></pre>
<p><img src="statistics_files/figure-html/axeslabels-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="linetypes-symbols-and-colors" class="section level4">
<h4><span class="header-section-number">3.4.1.1</span> Linetypes, Symbols, and Colors</h4>
<p>You can customize the scatterplot to draw lines between the points, or just draw lines without the point symbols with the <code>type</code> argument. This is not a sensible thing to for these data, but we demonstrate it anyway for completeness.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Lines and points</span>
<span class="kw">plot</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ,
     <span class="dt">xlab =</span> <span class="st">&quot;SAT Verbal&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;SAT Quantitative&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Relationship between SAT Scores&quot;</span>,
     <span class="dt">type =</span> <span class="st">&quot;o&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:lines1"></span>
<img src="statistics_files/figure-html/lines-1.png" alt="Points and lines with type='o'" width="672" />
<p class="caption">
Figure 3.1: Points and lines with type=‘o’
</p>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Just lines</span>
<span class="kw">plot</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ,
     <span class="dt">xlab =</span> <span class="st">&quot;SAT Verbal&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;SAT Quantitative&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Relationship between SAT Scores&quot;</span>,
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:lines2"></span>
<img src="statistics_files/figure-html/lines-2.png" alt="Just using lines with type='l'" width="672" />
<p class="caption">
Figure 3.2: Just using lines with type=‘l’
</p>
</div>
<p>You can also customise the types of symbols that are used for each point using the <code>pch</code>, the style of lines connecting these points using the <code>lty</code> argument, and the <code>col</code> argument to adjust the color of lines and symbol borders</p>
<p>With the <code>pch</code> argument, you specify the symbol used for each point using a numeric code. For example, the value <code>0</code> is the code for an unfilled square, while the value <code>15</code> is the value for a filled square with no border. Unfortunately, it has been scientifically proven that rememebering the code for all the possible symbols is impossible. Luckily, a helpful mnemonic device called a “chart” has been invented to help R programmers customize their plots. This chart is shown below:</p>
<p><img src="images/pch.png" /></p>
<p>Note that if you supply a character instead of a numeric values between 0 and 25, R will use that character as the plotting symbol. So, you could make a plot full of pound signs if you are so inclined!</p>
<p>The <code>lty</code> argument has a bit more flexibility. Line types can either be specified as an integer (0=blank, 1=solid (default), 2=dashed, 3=dotted, 4=dotdash, 5=longdash, 6=twodash) or as one of the character strings “blank”, “solid”, “dashed”, “dotted”, “dotdash”, “longdash”, or “twodash”.</p>
<p>The <code>col</code> argument accepts character string describing either a “built in” color name (see <code>?colors</code> for a list) or an RGB triplet encoded in hexadecimal notation. Unless you are intimately familiar with RGB color space, it’s a good idea to use a tool like the <a href="https://www.w3schools.com/colors/colors_picker.asp">W3 Organizations Online Color Picker</a> to help you figure out the RGB hex code for the color you want.</p>
<p>To demonstrate, lets take our original plot (with no lines) and customize it to use unfilled, magenta triangles:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Lines and points</span>
<span class="kw">plot</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ,
     <span class="dt">xlab =</span> <span class="st">&quot;SAT Verbal&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;SAT Quantitative&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Relationship between SAT Scores&quot;</span>,
     <span class="dt">col=</span><span class="st">&quot;magenta&quot;</span>, <span class="dt">pch=</span><span class="dv">2</span>)</code></pre>
<p><img src="statistics_files/figure-html/pch_and_col-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="adding-to-an-existing-plot" class="section level4">
<h4><span class="header-section-number">3.4.1.2</span> Adding to an existing plot</h4>
</div>
</div>
<div id="barplots" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Barplots</h3>
</div>
<div id="histograms" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Histograms</h3>
</div>
<div id="boxplots" class="section level3">
<h3><span class="header-section-number">3.4.4</span> Boxplots</h3>
</div>
<div id="configuring-plots" class="section level3">
<h3><span class="header-section-number">3.4.5</span> Configuring Plots</h3>
</div>
<div id="what-about-ggplot" class="section level3">
<h3><span class="header-section-number">3.4.6</span> What about ggplot?</h3>
</div>
</div>
<div id="inferential-statistics" class="section level2">
<h2><span class="header-section-number">3.5</span> Inferential Statistics</h2>
<div id="distribution-functions" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Distribution Functions</h3>
<p>The sections below introduce functions for executing common statistical tests. However, R’s family of distribution functions also make it possible to explore the underlying probability distributions for each test, and to carry out each test by hand. We therefore begin our demonstration of inferential statistics by giving an overview of these powerful intructional tools.</p>
<p>The full list of available distributions can be found <a href="https://en.wikibooks.org/wiki/R_Programming/Probability_Distributions">here</a>. The following table provides an overview the distributions that are likely to be relevant to you as an instructor, including the suffix that each distribution is identified by in the functions below:</p>
<table>
<thead>
<tr class="header">
<th align="left">Distribution</th>
<th align="left">Suffix</th>
<th align="left">Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Normal</td>
<td align="left"><code>norm</code></td>
<td align="left">mean, SD</td>
</tr>
<tr class="even">
<td align="left">Student’s T</td>
<td align="left"><code>t</code></td>
<td align="left">df, non-centrality</td>
</tr>
<tr class="odd">
<td align="left">Chi-Square</td>
<td align="left"><code>chisq</code></td>
<td align="left">df, non-centrality (non-negative)</td>
</tr>
<tr class="even">
<td align="left">F</td>
<td align="left"><code>f</code></td>
<td align="left">df<sub>1</sub>, df<sub>2</sub>, non-centrality</td>
</tr>
<tr class="odd">
<td align="left">Binomial</td>
<td align="left"><code>binom</code></td>
<td align="left">size (number of observations), probability</td>
</tr>
<tr class="even">
<td align="left">Uniform</td>
<td align="left"><code>unif</code></td>
<td align="left">minimum, maximum</td>
</tr>
</tbody>
</table>
<p>View the help documentation for default parameter values and additional details.</p>
<p>Each distribution can be accessed by a set of four functions, each labelled with the distribution’s suffix and a task-specific prefix:</p>
<table style="width:100%;">
<colgroup>
<col width="11%" />
<col width="77%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Prefix</th>
<th align="left">Task</th>
<th align="left">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">d</td>
<td align="left">Get the probability density associated with a point on the x-axis.</td>
<td align="left"><code>dnorm()</code></td>
</tr>
<tr class="even">
<td align="left">p</td>
<td align="left">Get the probability of a value above or below a point on the x-axis.</td>
<td align="left"><code>pnorm()</code></td>
</tr>
<tr class="odd">
<td align="left">q</td>
<td align="left">Get the x-axis value marking a cumulative probability.</td>
<td align="left"><code>qnorm()</code></td>
</tr>
<tr class="even">
<td align="left">r</td>
<td align="left">Get a random sample from the distribution.</td>
<td align="left"><code>rnorm()</code></td>
</tr>
</tbody>
</table>
<p>These functions are each demonstrated in the following sub-sections using the normal distribution. In these examples, consider that IQ scores are meant to be normally distributed with a mean of 100 and a standard deviation of 15:</p>
<p><img src="statistics_files/figure-html/IQ%20histogram%20with%20curve-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="getting-densities" class="section level4">
<h4><span class="header-section-number">3.5.1.1</span> Getting Densities</h4>
<p>The functions for getting the probability density associated with a point on the x-axis, such as <code>dnorm()</code> in the case of the normal distribution, are unlikely to come up in class. However, they may be useful for generating figures such as the one above, which was created with the following code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(<span class="kw">rnorm</span>(<span class="dv">10000</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>), <span class="dt">freq=</span><span class="ot">FALSE</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">.03</span>), <span class="dt">xlab=</span><span class="st">&#39;&#39;</span>, <span class="dt">main=</span><span class="st">&#39;IQ Scores&#39;</span>)
<span class="kw">points</span>(<span class="dt">x=</span><span class="kw">seq</span>(<span class="dv">40</span>, <span class="dv">160</span>, <span class="fl">.001</span>), <span class="dt">y=</span><span class="kw">dnorm</span>(<span class="kw">seq</span>(<span class="dv">40</span>, <span class="dv">160</span>, <span class="fl">.001</span>), <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>), <span class="dt">type=</span><span class="st">&#39;l&#39;</span>, <span class="dt">col=</span><span class="st">&#39;red&#39;</span>)</code></pre>
<p>Note that the input to <code>dnorm()</code> was a sequence of values from 40 to 160, by steps of .001. The output was the probability density for each value in the sequence. These values were then used to create a continuous curve that was added to the histogram of the data, in which the argument <code>freq=FALSE</code> ensured that the y-axis denoted probability densities instead of counts. A more detailed tutorial is provided <a href="https://homepage.divms.uiowa.edu/~luke/classes/STAT4580/histdens.html">here</a>.</p>
</div>
<div id="getting-probabilities" class="section level4">
<h4><span class="header-section-number">3.5.1.2</span> Getting Probabilities</h4>
<p>You can use <code>pnorm()</code> to demonstrate that there is a 9.12% chance of getting an IQ score that is less than or equal to 80:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">80</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</code></pre>
<pre><code>## [1] 0.09121122</code></pre>
<p>To find the probability of getting a value <em>greater than</em> or equal to a cutoff, such as 80, you can either add the argument <code>lower.tail=FALSE</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">80</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>, <span class="dt">lower.tail=</span><span class="ot">FALSE</span>)</code></pre>
<pre><code>## [1] 0.9087888</code></pre>
<p>…or, since the area under the curve sums to 1, you can subtract the output of the previous command from 1:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(<span class="dv">80</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</code></pre>
<pre><code>## [1] 0.9087888</code></pre>
<p>The latter method may be better for instructional purposes.</p>
</div>
<div id="getting-quantiles" class="section level4">
<h4><span class="header-section-number">3.5.1.3</span> Getting Quantiles</h4>
<p>You can use <code>qnorm()</code> to demonstrate that an IQ score of 124.67 marks the 95th percentile of scores:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(.<span class="dv">95</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</code></pre>
<pre><code>## [1] 124.6728</code></pre>
<p>Similarly, you can add the argument <code>lower.tail=FALSE</code> to see the point on the x-axis that marks the <em>top</em> 95% of scores:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(.<span class="dv">95</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>, <span class="dt">lower.tail=</span><span class="ot">FALSE</span>)</code></pre>
<pre><code>## [1] 75.3272</code></pre>
<p>Note that subtracting from 1 does not work here as it did with <code>pnorm()</code> because the output of <code>qnorm()</code> is a quantile, which does not need to sum to 1 as probabilities do.</p>
</div>
<div id="getting-random-samples" class="section level4">
<h4><span class="header-section-number">3.5.1.4</span> Getting Random Samples</h4>
<p>You can use <code>rnorm()</code> to randomly sample a class of 50 students from the population of IQ scores:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</code></pre>
<pre><code>##  [1]  93.41420  95.70582  94.53327 123.12357 106.61557 132.14654  99.19861
##  [8]  68.58907 101.46172  98.32712 102.64417 111.42898 100.05772  90.97660
## [15] 106.72652  87.06458  80.24276 119.41905  99.21840  81.79788 111.21179
## [22]  80.32440  93.03009  91.92552  88.65017 113.00005  85.63063 113.33810
## [29]  91.79288  72.37315 112.36956  68.88669  85.24275 120.51950  80.91796
## [36]  79.16941  86.06339 105.17669 109.64150 115.37794  94.64986 128.26509
## [43]  97.52261 114.19445  93.51780  96.81953  78.88929  99.00226 109.89992
## [50] 112.40981</code></pre>
</div>
<div id="running-statistical-tests-by-hand" class="section level4">
<h4><span class="header-section-number">3.5.1.5</span> Running Statistical Tests by Hand</h4>
<p>These functions can be used to conduct statistical analyses by hand. Consider a demonstration of a z-test using the functions for the normal distribution. To test whether an IQ score of 135 is significantly different from the mean IQ score, first find the z-score:</p>
<pre class="sourceCode r"><code class="sourceCode r">IQ135_z &lt;-<span class="st"> </span>(<span class="dv">135-100</span>)<span class="op">/</span><span class="dv">15</span>
IQ135_z</code></pre>
<pre><code>## [1] 2.333333</code></pre>
<p>You could then compare that z-score to the critical z-scores associated with an alpha of .05, here assuming a two-tailed hypothesis:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(.<span class="dv">025</span>)</code></pre>
<pre><code>## [1] -1.959964</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(.<span class="dv">975</span>)</code></pre>
<pre><code>## [1] 1.959964</code></pre>
<p>The z-score of an IQ of 135 is greater than the critical z-score for the upper tail, so we can reject the null hypothesis. Note that for a one-tailed hypothesis, simply use one call to <code>qnorm()</code> with .05 or .95 for the lower or upper tail, respectively.</p>
<p>Alternatively, you could find the probability of getting a z-score that if equal to the test score or more extreme (in this case, more positive), and compare that to the alpha value instead of the critical z-score:</p>
<pre class="sourceCode r"><code class="sourceCode r">IQ135_z_prob &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(IQ135_z)</code></pre>
<p>The probability of getting an IQ of 135 is less than alpha (either .025 for a two-tailed hypothesis or .05 for a one-tailed hypothesis), so we reject the null hypothesis.</p>
<p>Note that you could also apply this method by finding the probability of an IQ of 135 given a mean of 100 and standard deviation of 15, and compare that to the alpha value instead:</p>
<pre class="sourceCode r"><code class="sourceCode r">IQ135_prob &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(<span class="dv">135</span>, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</code></pre>
<p>This provides the same probability as for the z-score, so we make the same conclusion. However, though it uses one line of code instead of two, you may find that this method is more confusing for some students, particularly if they are used to seeing distributions centered on 0 elsewhere in the course.</p>
<p>This same process can be extended to a range of statistical tests, including t tests, F tests, Chi-Square tests, and binomial tests.</p>
</div>
</div>
<div id="t.test" class="section level3">
<h3><span class="header-section-number">3.5.2</span> <code>t.test()</code></h3>
<p>The <code>t.test()</code> function can be used to execute one-sample, paired, or two-sample t-tests. Each case is demonstrated below, but first note three general arguments that can be used to augment the test:</p>
<table>
<colgroup>
<col width="10%" />
<col width="89%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Argument</th>
<th align="left">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>alternative</code></td>
<td align="left">Set to <code>two.sided</code> for a two-sided test, <code>less</code> for the lower tail, and <code>greater</code> for the upper tail; the default is <code>two.sided</code>.</td>
</tr>
<tr class="even">
<td align="left"><code>var.equal</code></td>
<td align="left">Set to <code>TRUE</code> to assume equal variance and <code>FALSE</code> otherwise; the default is <code>FALSE</code>.</td>
</tr>
<tr class="odd">
<td align="left"><code>conf.level</code></td>
<td align="left">Provide a number between 0 and 1 to specify the range for the confidence interval; the default is .95.</td>
</tr>
</tbody>
</table>
<div id="one-sample-t-tests" class="section level4">
<h4><span class="header-section-number">3.5.2.1</span> One-sample t-tests</h4>
<p>To demonstrate a one-sample t-test, imagine that we are curious whether the average verbal SAT score in the <code>sat.act</code> data set is different from 0. We could test that question with the following call:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(sat.act<span class="op">$</span>SATV)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  sat.act$SATV
## t = 143.47, df = 699, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  603.8560 620.6126
## sample estimates:
## mean of x 
##  612.2343</code></pre>
<p>The output of <code>t.test()</code> gives us a nice summary of the results, including the t-statistic, degrees of freedom, p-value, and 95% confidence interval. The p-value is essentially 0, so we can reject the null hypothesis that the average verbal SAT score is 0.</p>
<p>If we wanted to instead see if the average verbal SAT score was different from 650, we could change the null comparison value by setting the <code>mu</code> parameter:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(sat.act<span class="op">$</span>SATV, <span class="dt">mu=</span><span class="dv">600</span>)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  sat.act$SATV
## t = 2.867, df = 699, p-value = 0.004269
## alternative hypothesis: true mean is not equal to 600
## 95 percent confidence interval:
##  603.8560 620.6126
## sample estimates:
## mean of x 
##  612.2343</code></pre>
<p>The p-value is 0.004, so we can reject the null hypothesis that the average verbal SAT score is 600. Instead, it appears to be significantly higher.</p>
</div>
<div id="paired-t-tests" class="section level4">
<h4><span class="header-section-number">3.5.2.2</span> Paired t-tests</h4>
<p>To demonstrate a paired t-test, imagine that we are curious as to whether verbal SAT scores are different from quantitative SAT scores. We can conduct this in one of two ways.</p>
<p>First, we could calculate the difference score for each pair, then run a one-sample t-test comparing the average difference score to 0:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Calculate difference scores</span>
sat.act<span class="op">$</span>SAT_diff &lt;-<span class="st"> </span>sat.act<span class="op">$</span>SATV<span class="op">-</span>sat.act<span class="op">$</span>SATQ

<span class="co"># Run a one-sample t-test</span>
<span class="kw">t.test</span>(sat.act<span class="op">$</span>SAT_diff)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  sat.act$SAT_diff
## t = 0.57483, df = 686, p-value = 0.5656
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -5.116109  9.351917
## sample estimates:
## mean of x 
##  2.117904</code></pre>
<p>The p-value is .566, so we fail to reject the null hypothesis that the difference between verbal and quantitative SAT scores are approximately zero.</p>
<p>In the second method, we could have <code>t.test()</code> compute the difference scores for us by specifying both samples and setting the <code>paired</code> argument to <code>TRUE</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(sat.act<span class="op">$</span>SATV, sat.act<span class="op">$</span>SATQ, <span class="dt">paired=</span><span class="ot">TRUE</span>)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  sat.act$SATV and sat.act$SATQ
## t = 0.57483, df = 686, p-value = 0.5656
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.116109  9.351917
## sample estimates:
## mean of the differences 
##                2.117904</code></pre>
<p>We get exactly the same result. However, note that though this method uses fewer lines of code it risks obscuring the role of difference scores for the student.</p>
</div>
<div id="two-sample-t-tests" class="section level4">
<h4><span class="header-section-number">3.5.2.3</span> Two-sample t-tests</h4>
<p>To demonstrate a two-sample t-test, imagine that we are curious as to whether male and female students reported different quantitative SAT scores.</p>
<p>The function call is very similar to the second method for conducting a paired t-test, but we set the <code>paired</code> argument to <code>FALSE</code> instead:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(sat.act<span class="op">$</span>SATQ[sat.act<span class="op">$</span>gender<span class="op">==</span><span class="dv">1</span>], sat.act<span class="op">$</span>SATQ[sat.act<span class="op">$</span>gender<span class="op">==</span><span class="dv">2</span>], <span class="dt">paired=</span><span class="ot">FALSE</span>)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sat.act$SATQ[sat.act$gender == 1] and sat.act$SATQ[sat.act$gender == 2]
## t = 4.3544, df = 492.94, p-value = 1.624e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  21.88433 57.87165
## sample estimates:
## mean of x mean of y 
##  635.8735  595.9955</code></pre>
<p>The p-value is approximately .00002, so we can reject the null hypothesis that male and female students report essentially the same quantitative SAT scores. Instead, the mean score for males appears to be significantly higher.</p>
<p>Note that the default value for the <code>paired</code> argument is <code>FALSE</code>, so running the above call with the <code>paired</code> argument omitted would produce the same result. However, you might want to encourage students to always specify the argument for a t-test with two samples so that they can be sure they are running the intended test.</p>
<p>Further, note that the above example indexes the male and female groups within the call to <code>t.test()</code>, but you could also ask students to do this separately beforehand:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Subset the groups</span>
male_SATQ &lt;-<span class="st"> </span>sat.act<span class="op">$</span>SATQ[sat.act<span class="op">$</span>gender<span class="op">==</span><span class="dv">1</span>]
female_SATQ &lt;-<span class="st"> </span>sat.act<span class="op">$</span>SATQ[sat.act<span class="op">$</span>gender<span class="op">==</span><span class="dv">2</span>]

<span class="co"># Run a two-sample t-test</span>
<span class="kw">t.test</span>(male_SATQ, female_SATQ, <span class="dt">paired=</span><span class="ot">FALSE</span>)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  male_SATQ and female_SATQ
## t = 4.3544, df = 492.94, p-value = 1.624e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  21.88433 57.87165
## sample estimates:
## mean of x mean of y 
##  635.8735  595.9955</code></pre>
</div>
</div>
<div id="aov" class="section level3">
<h3><span class="header-section-number">3.5.3</span> <code>aov()</code></h3>
<p>The <code>aov()</code> command can be used to execute an ANOVA. The basic call includes one argument, which is a formula object. Whether <code>aov()</code> is used to run a one-way, two-way, or multi-way ANOVA, with or without interaction terms, is based entirely on the formula.</p>
<div id="one-way-anova" class="section level4">
<h4><span class="header-section-number">3.5.3.1</span> One-way ANOVA</h4>
<p>To demonstrate a one-way ANOVA, imagine that we are curious as to whether verbal SAT scores vary across education level:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(sat.act<span class="op">$</span>SATV <span class="op">~</span><span class="st"> </span>sat.act<span class="op">$</span>education)</code></pre>
<pre><code>## Call:
##    aov(formula = sat.act$SATV ~ sat.act$education)
## 
## Terms:
##                 sat.act$education Residuals
## Sum of Squares              19247   8890899
## Deg. of Freedom                 1       698
## 
## Residual standard error: 112.8613
## Estimated effects may be unbalanced</code></pre>
<p>The standard output of aov does not contain readily interpretable results. To get the ANOVA table, it is better to save the output of <code>aov()</code>, then call <code>summary()</code> on that saved object:</p>
<pre class="sourceCode r"><code class="sourceCode r">educ_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(sat.act<span class="op">$</span>SATV <span class="op">~</span><span class="st"> </span>sat.act<span class="op">$</span>education)
<span class="kw">summary</span>(educ_aov)</code></pre>
<pre><code>##                    Df  Sum Sq Mean Sq F value Pr(&gt;F)
## sat.act$education   1   19247   19247   1.511  0.219
## Residuals         698 8890899   12738</code></pre>
<p>Now we can see that the p-value is greater than an alpha of .05, so we fail to reject the null hypothesis that verbal SAT scores are equal across levels of education.</p>
<p>We might neaten up our code a bit by using the <code>data</code> argument to specify the data frame that our variables belong to. This allows us to just use the column names in the formula object:</p>
<pre class="sourceCode r"><code class="sourceCode r">educ_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(SATV <span class="op">~</span><span class="st"> </span>education, <span class="dt">data=</span>sat.act)
<span class="kw">summary</span>(educ_aov)</code></pre>
<pre><code>##              Df  Sum Sq Mean Sq F value Pr(&gt;F)
## education     1   19247   19247   1.511  0.219
## Residuals   698 8890899   12738</code></pre>
</div>
<div id="two-way-anova" class="section level4">
<h4><span class="header-section-number">3.5.3.2</span> Two-way ANOVA</h4>
<p>To demonstrate a two-way ANOVA, imagine that we are curious as to whether quantitative SAT scores vary across levels of education and gender:</p>
<pre class="sourceCode r"><code class="sourceCode r">educ_gender_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(SATQ <span class="op">~</span><span class="st"> </span>education <span class="op">+</span><span class="st"> </span>gender, <span class="dt">data=</span>sat.act)
<span class="kw">summary</span>(educ_gender_aov)</code></pre>
<pre><code>##              Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## education     1   10998   10998   0.845    0.358    
## gender        1  261978  261978  20.133 8.47e-06 ***
## Residuals   684 8900522   13012                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 13 observations deleted due to missingness</code></pre>
<p>The p-value for education is .358, so we fail to reject the null hypothesis that quantitative SAT scores are equal across levels of education. The p-value for gender, however, is approximately zero, so we can reject the null hypothesis that quantitative SAT scores are equal across genders. To determine which gender has the highest scores, you might have your students find the means or create a barplot.</p>
<p>The two-way ANOVA that we just ran assumed an additive model, but perhaps we think that the effect of gender on quantitative SAT scores is different across different levels of education. To test this hypothesis with the interactive model, change the <code>+</code> symbol between the independent variables to an <code>*</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">educ_gender_aov_int &lt;-<span class="st"> </span><span class="kw">aov</span>(SATQ <span class="op">~</span><span class="st"> </span>education <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data=</span>sat.act)
<span class="kw">summary</span>(educ_gender_aov_int)</code></pre>
<pre><code>##                   Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## education          1   10998   10998   0.844    0.358    
## gender             1  261978  261978  20.111 8.57e-06 ***
## education:gender   1    3396    3396   0.261    0.610    
## Residuals        683 8897126   13027                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 13 observations deleted due to missingness</code></pre>
<p>The p-value for the interaction term is .610, so we fail to reject the null hypothesis that the effect of gender on quantitative SAT scores is the same across levels of education.</p>
</div>
</div>
<div id="cor.test" class="section level3">
<h3><span class="header-section-number">3.5.4</span> <code>cor.test()</code></h3>
</div>
<div id="binom.test" class="section level3">
<h3><span class="header-section-number">3.5.5</span> <code>binom.test()</code></h3>
</div>
<div id="chisq.test" class="section level3">
<h3><span class="header-section-number">3.5.6</span> <code>chisq.test()</code></h3>
</div>
<div id="lm" class="section level3">
<h3><span class="header-section-number">3.5.7</span> <code>lm()</code></h3>
</div>
<div id="confidence-intervals" class="section level3">
<h3><span class="header-section-number">3.5.8</span> Confidence Intervals</h3>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-programming-fundamentals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tools-advice-for-instructors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["PBS-R-Manual.pdf"],
"toc": {
"collapse": "none"
},
"toc_depth": 2
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
